# Auto-generated from responses_api.py
# Model: Annotation

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from typing import Union

from pydantic import BaseModel, Field



# Model dependencies
from .container_file_citation_body import ContainerFileCitationBody
from .file_citation_body import FileCitationBody
from .file_path import FilePath
from .url_citation_body import UrlCitationBody


class Annotation(BaseModel):
    __root__: Union[
        FileCitationBody, UrlCitationBody, ContainerFileCitationBody, FilePath
    ] = Field(..., discriminator='type')
