# Auto-generated from responses_api.py
# Model: ComputerAction

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from typing import Union

from pydantic import BaseModel, Field



# Model dependencies
from .click_param import ClickParam
from .double_click_action import DoubleClickAction
from .drag import Drag
from .key_press_action import KeyPressAction
from .move import Move
from .screenshot import Screenshot
from .scroll import Scroll
from .type_model import TypeModel
from .wait import Wait


class ComputerAction(BaseModel):
    __root__: Union[
        ClickParam,
        DoubleClickAction,
        Drag,
        KeyPressAction,
        Move,
        Screenshot,
        Scroll,
        TypeModel,
        Wait,
    ] = Field(..., discriminator='type')
