# Auto-generated from responses_api.py
# Model: ComparisonFilterValueItems

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from typing import Union

from pydantic import BaseModel




class ComparisonFilterValueItems(BaseModel):
    __root__: Union[str, float]
