# Auto-generated from responses_api.py
# Model: Config

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import AnyUrl, BaseModel, Extra, Field, confloat, conint, constr




    class Config:
        extra = Extra.forbid
