# Auto-generated from responses_api.py
# Model: Filters

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from typing import Union

from pydantic import BaseModel



# Model dependencies
from .comparison_filter import ComparisonFilter
from .compound_filter import CompoundFilter


class Filters(BaseModel):
    __root__: Union[ComparisonFilter, CompoundFilter]
