# Auto-generated from responses_api.py
# Model: FunctionAndCustomToolCallOutput

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from typing import Union

from pydantic import BaseModel, Field



# Model dependencies
from .input_file_content import InputFileContent
from .input_image_content import InputImageContent
from .input_text_content import InputTextContent


class FunctionAndCustomToolCallOutput(BaseModel):
    __root__: Union[InputTextContent, InputImageContent, InputFileContent] = Field(
        ..., discriminator='type'
    )
