# Auto-generated from responses_api.py
# Model: InputMessageContentList

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from typing import List

from pydantic import BaseModel, Field



# Model dependencies
from .input_content import InputContent


class InputMessageContentList(BaseModel):
    __root__: List[InputContent] = Field(
        ...,
        description='A list of one or many input items to the model, containing different content \ntypes.\n',
        title='Input item content list',
    )
