# Auto-generated from responses_api.py
# Model: Metadata

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from typing import Dict, Optional

from pydantic import BaseModel




class Metadata(BaseModel):
    __root__: Optional[Dict[str, str]]
