# Auto-generated from responses_api.py
# Model: ModelIdsResponses

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from typing import Union

from pydantic import BaseModel, Field



# Model dependencies
from .model_ids_responses1 import ModelIdsResponses1
from .model_ids_shared import ModelIdsShared


class ModelIdsResponses(BaseModel):
    __root__: Union[ModelIdsShared, ModelIdsResponses1] = Field(..., example='gpt-4o')
