# Auto-generated from responses_api.py
# Model: ModelIdsShared

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from typing import Union

from pydantic import BaseModel, Field



# Model dependencies
from .chat_model import ChatModel


class ModelIdsShared(BaseModel):
    __root__: Union[str, ChatModel] = Field(..., example='gpt-4o')
