# Auto-generated from responses_api.py
# Model: OutputMessageContent

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from typing import Union

from pydantic import BaseModel, Field



# Model dependencies
from .output_text_content import OutputTextContent
from .refusal_content import RefusalContent


class OutputMessageContent(BaseModel):
    __root__: Union[OutputTextContent, RefusalContent] = Field(
        ..., discriminator='type'
    )
