# Auto-generated from responses_api.py
# Model: Prompt

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from typing import Optional

from pydantic import BaseModel



# Model dependencies
from .prompt1 import Prompt1


class Prompt(BaseModel):
    __root__: Optional[Prompt1]
