# Auto-generated from responses_api.py
# Model: RequireApproval

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from typing import Optional

from pydantic import BaseModel, Extra



# Model dependencies
from .m_c_p_tool_filter import MCPToolFilter


class RequireApproval(BaseModel):
    class Config:
        extra = Extra.forbid

    always: Optional[MCPToolFilter] = None
    never: Optional[MCPToolFilter] = None
