# Auto-generated from responses_api.py
# Model: ResponseFormatJsonSchemaSchema

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00



from pydantic import BaseModel, Extra




class ResponseFormatJsonSchemaSchema(BaseModel):
    pass

    class Config:
        extra = Extra.allow
