# Auto-generated from responses_api.py
# Model: ResponseStreamOptions

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from typing import Optional

from pydantic import BaseModel



# Model dependencies
from .response_stream_options1 import ResponseStreamOptions1


class ResponseStreamOptions(BaseModel):
    __root__: Optional[ResponseStreamOptions1]
