# Auto-generated from responses_api.py
# Model: ServiceTier

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from typing import Optional

from pydantic import BaseModel



# Model dependencies
from .service_tier1 import ServiceTier1


class ServiceTier(BaseModel):
    __root__: Optional[ServiceTier1]
