# Auto-generated from responses_api.py
# Model: TextResponseFormatConfiguration

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from typing import Union

from pydantic import BaseModel, Field



# Model dependencies
from .response_format_json_object import ResponseFormatJsonObject
from .response_format_text import ResponseFormatText
from .text_response_format_json_schema import TextResponseFormatJsonSchema


class TextResponseFormatConfiguration(BaseModel):
    __root__: Union[
        ResponseFormatText, TextResponseFormatJsonSchema, ResponseFormatJsonObject
    ] = Field(
        ...,
        description='An object specifying the format that the model must output.\n\nConfiguring `{ "type": "json_schema" }` enables Structured Outputs, \nwhich ensures the model will match your supplied JSON schema. Learn more in the \n[Structured Outputs guide](https://platform.openai.com/docs/guides/structured-outputs).\n\nThe default format is `{ "type": "text" }` with no additional options.\n\n**Not recommended for gpt-4o and newer models:**\n\nSetting to `{ "type": "json_object" }` enables the older JSON mode, which\nensures the message the model generates is valid JSON. Using `json_schema`\nis preferred for models that support it.\n',
        discriminator='type',
    )
