# Auto-generated from responses_api.py
# Model: Tool

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from typing import Union

from pydantic import BaseModel, Field



# Model dependencies
from .code_interpreter_tool import CodeInterpreterTool
from .computer_use_preview_tool import ComputerUsePreviewTool
from .custom_tool_param import CustomToolParam
from .file_search_tool import FileSearchTool
from .function_tool import FunctionTool
from .image_gen_tool import ImageGenTool
from .local_shell_tool_param import LocalShellToolParam
from .m_c_p_tool import MCPTool
from .web_search_preview_tool import WebSearchPreviewTool
from .web_search_tool import WebSearchTool


class Tool(BaseModel):
    __root__: Union[
        FunctionTool,
        FileSearchTool,
        ComputerUsePreviewTool,
        WebSearchTool,
        MCPTool,
        CodeInterpreterTool,
        ImageGenTool,
        LocalShellToolParam,
        CustomToolParam,
        WebSearchPreviewTool,
    ] = Field(
        ...,
        description='A tool that can be used to generate a response.\n',
        discriminator='type',
    )
