# Auto-generated from responses_api.py
# Model: VectorStoreFileAttributes

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from typing import Dict, Optional, Union

from pydantic import BaseModel, constr




class VectorStoreFileAttributes(BaseModel):
    __root__: Optional[Dict[str, Union[constr(max_length=512), float, bool]]]
