# Auto-generated from responses_api.py
# Model: Verbosity

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from typing import Optional

from pydantic import BaseModel



# Model dependencies
from .verbosity1 import Verbosity1


class Verbosity(BaseModel):
    __root__: Optional[Verbosity1]
