# Auto-generated from responses_api.py
# Model: WebSearchApproximateLocation

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from typing import Optional

from pydantic import BaseModel



# Model dependencies
from .web_search_approximate_location1 import WebSearchApproximateLocation1


class WebSearchApproximateLocation(BaseModel):
    __root__: Optional[WebSearchApproximateLocation1]
